'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace AspNetWebFormsPivotFieldCalculationBindings
    
    Partial Public Class _Default
        
        '''<summary>
        '''ASPxPivotGrid1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ASPxPivotGrid1 As Global.DevExpress.Web.ASPxPivotGrid.ASPxPivotGrid
        
        '''<summary>
        '''fieldCountry control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fieldCountry As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
        
        '''<summary>
        '''fieldCategoryName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fieldCategoryName As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
        
        '''<summary>
        '''fieldProductName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fieldProductName As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
        
        '''<summary>
        '''fieldExtendedPrice control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fieldExtendedPrice As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
        
        '''<summary>
        '''fieldRank control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fieldRank As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
        
        '''<summary>
        '''fieldPercentOfTotal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fieldPercentOfTotal As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
        
        '''<summary>
        '''fieldMovingCalculation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fieldMovingCalculation As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
        
        '''<summary>
        '''fieldRunningTotal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fieldRunningTotal As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
        
        '''<summary>
        '''fieldExpressions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fieldExpressions As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
        
        '''<summary>
        '''fieldDifference control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fieldDifference As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
        
        '''<summary>
        '''fieldWindowExpression control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fieldWindowExpression As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField
        
        '''<summary>
        '''SqlDataSource1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SqlDataSource1 As Global.System.Web.UI.WebControls.SqlDataSource
    End Class
End Namespace
